### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by thams** [xujiahuayz/bondingcurves#13]
python -m amms.analysis
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/thams/Documents/jupyter/bondingcurves/amms/analysis.py", line 6, in <module>
    from amms.balancer.main import Balancer
  File "/Users/thams/Documents/jupyter/bondingcurves/amms/balancer/main.py", line 1, in <module>
    from amms.main import Amm
  File "/Users/thams/Documents/jupyter/bondingcurves/amms/main.py", line 2, in <module>
    class Amm:
  File "/Users/thams/Documents/jupyter/bondingcurves/amms/main.py", line 3, in Amm
    def __init__(self, reserves: list[int], weights: list[float]):
TypeError: 'type' object is not subscriptable

**Comment by thams** [comment]
solved by moving from python 3.8.10 to 3.9.1
